sudo: required
dist: trusty
services:
- docker
install:
- docker build -t test .
script:
- docker run -ti test /bin/true
- docker run -ti test /bin/bash --version
notifications:
  email: false
  slack:
    secure: jug75+3mgc6/o9NvBEEUlnlSDzGIPRNpuGA7V5GZJ8EIhssOedlEJfneiwTQCd8Gth3C1NrblbkR08YMLLHPU1J9cKCRs2tzSR1Jxhv0kueVI3Wli0JiYeN0XHYZqRKADlhCs61S7+WUQN/5EXSvzITXjcu4vVLExp4exHFaLGLRtxUrc3dXZChKVFS3lzwpDM/aWJs81YJnjVJGJVUvqxN/ZM9igQ8c2Xq00gq1EWoykccqUg3zAqa9/dkaAxaLLfTKJHQ4dmMxDSHcW1MMxyprZa0ZtmHc60QR4tecicWmMnL+vfF+s6RhZVdLK9FYDZpaDvg/zGk+E2iOSfp+N2HGcFYhbV8DD+qlo+QMHP62Wg7qsjSsm4Ka2cQf/JlIr+OkiF16YDhNuUacXaUIh18yjxiAK1xq/eoIY4a/SgYIf79IlYRtxj08WdEQ6/h8jB4BY0wOLUqTrrSghAFyIVLpEu/36s8vHggEUac4jKmQTcRJhxI61c+FM6iY+AGmDeNiM1v292dn/yaD90zjI3hDWFShMr4YzfgdsE2pnmzR4f5jOfvBglXUH9aliEDeV+OUtus6zqDvAoZSY4aY9JWW+DAm1Q4r6PDORYDLnxzwP0cAd7TlemKFOvYPrnu6IP8d0zIb1coX3X+yFSyoJeNf2ZEfoB/1Q1Y0/YZ15bA=
